version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mymainpassword
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerceuser
      MYSQL_PASSWORD: ecommercepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  java_app:
    build: .
    container_name: java_app_container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ecommerceuser
      SPRING_DATASOURCE_PASSWORD: ecommercepass
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: